// <auto-generated />
using System;
using KayipEsyaTakip.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace KayipEsyaTakip.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031115045_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("KAYIP_ESYA_APP")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KayipEsyaTakip.API.Models.KayipEsya", b =>
                {
                    b.Property<int>("EsyaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EsyaId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("BulanKisi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("BulunduguTarih")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("BulunduguYer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("EsyaTuru")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("TeslimAlanPersonel")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("TeslimAlinanBirim")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("EsyaId");

                    b.ToTable("KayipEsyalar", "KAYIP_ESYA_APP");
                });

            modelBuilder.Entity("KayipEsyaTakip.API.Models.Teslimat", b =>
                {
                    b.Property<int>("TeslimatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeslimatId"));

                    b.Property<int>("EsyaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("KayipEsyaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TeslimAlanAdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("TeslimAlanTc")
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<string>("TeslimEdenPersonel")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("TeslimTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasDefaultValueSql("SYSDATE");

                    b.HasKey("TeslimatId");

                    b.HasIndex("EsyaId");

                    b.ToTable("Teslimatlar", "KAYIP_ESYA_APP");
                });

            modelBuilder.Entity("KayipEsyaTakip.API.Models.Teslimat", b =>
                {
                    b.HasOne("KayipEsyaTakip.API.Models.KayipEsya", "KayipEsya")
                        .WithMany("Teslimatlar")
                        .HasForeignKey("EsyaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KayipEsya");
                });

            modelBuilder.Entity("KayipEsyaTakip.API.Models.KayipEsya", b =>
                {
                    b.Navigation("Teslimatlar");
                });
#pragma warning restore 612, 618
        }
    }
}
